[package]
name = "nu_plugin_parse-sce-elf"
version = "0.1.0"
edition = "2021"

[dependencies]
goblin = { version = "0.5.3", default-features = false, features = ["std", "elf32", "elf64", "endian_fd"] }
serde = { version = "1.0.140", features = ["derive"] }
serde_json = "1.0.82"
